### ISSUE TITLE
Windows path resolve issue with actions

### ISSUE THREAD

**Issue by LUISMAGAIVER341** [brisa-build/brisa#691]
**Describe the bug**
Basically it gives a error that can't compile actions.

**To Reproduce**

1. Open the terminal
2. `bun create brisa@latest`
3. cd on the directory and `bun install` to certify the fresh install
4. `bun dev` or `brisa dev` to run
5. Voilà! The error

**Expected behavior**
Clear and error less output

**Screen recording**
![image](https://github.com/user-attachments/assets/2c578624-7b8f-401a-9f67-1b194a2dfd5f)

**NOTE**
The site renders
![image](https://github.com/user-attachments/assets/a77bfde2-cb9f-4a31-9e6d-f6340efa8ad1)
But i think it didn't completely.

**Comment by LUISMAGAIVER341** [comment]
Well... I think i found a solution. if you delete <PROJECT>/build/pages/index.js
It stops.

**Comment by aralroca** [comment]
It looks like bad path resolution in Windows: 

<img width="1313" alt="Screenshot 2024-12-22 at 20 07 31" src="https://github.com/user-attachments/assets/e740bd16-6c08-418d-85fd-8ebc0cbcbca7" />

We are already using `join` to use the correct platform separators:

https://github.com/brisa-build/brisa/blob/32336a6f53c7b31d0d1cf933ac596135af5564df/packages/brisa/src/utils/transpile-actions/index.ts#L600

I see you have Bun 1.1.38, this had several regressions and currently there is 1.1.42. Could you check if it is fixed? This used to work fine in previous versions of Bun. Related to this old Windows issue https://github.com/brisa-build/brisa/issues/538

thank you for reporting it @LUISMAGAIVER341

**Comment by Jaishree2310** [comment]
@aralroca Can you please assign this to me?

**Comment by aralroca** [comment]
@Jaishree2310 sure 😊 thanks!

**Comment by LUISMAGAIVER341** [comment]
Thx!

**Comment by aralroca** [comment]
@Jaishree2310 do you need some context? Feel free to ask me anything on [Discord](https://brisa.build/discord) or here.

**Comment by BrainInJar** [comment]
I have the same problem

![Image](https://github.com/user-attachments/assets/6f963db8-f085-49c3-8306-14f3b4b0889e)

**Comment by aralroca** [comment]
The problem has not been solved yet. Anyone who has Windows and wants to contribute is super welcome. Otherwise, I will take care of this bug as soon as possible. Thanks for the reminder @BrainInJar

**Comment by LUISMAGAIVER341** [comment]
Ok, what i need to know and what i should do to be part of team? or at least help with this bug?

**Comment by aralroca** [comment]
@LUISMAGAIVER341 you can create some example (https://brisa.build/examples), clone the Brisa repo, and use symlink to Brisa to fix the code and verify that it is solving the issue. Symlink sometimes does not work so well, if is the case, you can use a hardcoded symlink script like:

```ts
    "symlink": "cd ../brisa/packages/brisa && bun run build && cp -R * ../../../example-project/node_modules/brisa/ && cd ../../../example-project && bun dev",
```

The important things are:


- Identify the problem
- Add a failing test of the problem
- Fix this failing test
- Verify that the example is working fine with Windows.

Probably the issue is related to some Window separator `\` of the paths.

**Comment by LUISMAGAIVER341** [comment]
Not exactly that.
Powershell does suporte Unix like pathnames but not the case of CMD.
This is probably the solution cuz It Will work on both CMD and pwsh

**Comment by LUISMAGAIVER341** [comment]
What is kinda weird is pwsh not recognizing the pathname.
Yeah, i use pwsh

**Comment by tommy141x** [comment]
I can't even build the brisa package itself on windows, results in a Bun panic.

1. ``git clone https://github.com/brisa-build/brisa.git``
2. Tried installing and building in both the root dir and in ``/packages/brisa``:

``/packages/brisa``:
```shell
➜  brisa git:(canary) bun i
bun install v1.2.9 (9a329c04)
  📦 Installing [25/293]
error: failed to enqueue lifecycle scripts for sharp: SyntaxError
  ⚙️  esbuild [1/1] C:\Users\Tommy\Documents\brisa-test\brisa\node_modules\esbuild\install.js:163
  let offset = 0;
  ^^^

SyntaxError: Unexpected strict mode reserved word
    at wrapSafe (node:internal/modules/cjs/loader:1486:18)
    at Module._compile (node:internal/modules/cjs/loader:1528:20)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49

Node.js v22.14.0

error: postinstall script from "esbuild" exited with 1
➜  brisa git:(canary) bun run build
$ bun run clean && bun run build:jsx-runtime && bun run build:jsx-dev-runtime && bun run build:core && bun run build:core-client && bun run build:core-server && bun run build:core-macros && bun run build:core-test && bun run build:core-compiler
$ rm -rf out jsx-runtime jsx-dev-runtime cli client server cli.js
$ bun build --minify --target=bun --outdir=jsx-runtime src/jsx-runtime/index.ts && cp src/types/index.d.ts jsx-runtime/index.d.ts
Bundled 1 module in 16ms

  index.js  451 bytes  (entry point)

$ bun build --minify --target=bun --outdir=jsx-dev-runtime src/jsx-runtime/index.ts && cp src/types/index.d.ts jsx-dev-runtime/index.d.ts
Bundled 1 module in 9ms

  index.js  451 bytes  (entry point)

$ bun build --minify --outdir=out/core src/core/index.ts && bun run build:bin && cp src/types/index.d.ts out/core/index.d.ts
Bundled 11 modules in 35ms

  index.js  3.65 KB  (entry point)

$ bun build --minify --target=bun --outdir=./ src/bin/index.ts && bun run build:cli-utils && bun run build:cli-serve-dev
Bundled 4 modules in 29ms

  index.js  13.86 KB  (entry point)

$ bun build --minify --target=bun --outdir=out/cli src/cli/build.ts src/cli/build-standalone/index.ts && bun build --minify --target=node --outdir=out/cli src/cli/serve/index.tsx src/cli/integrations/mdx/index.ts src/cli/integrations/tailwindcss/index.ts src/cli/integrations/pandacss/index.ts --external brisa-project-internals
============================================================
Bun v1.2.9 (9a329c04) Windows x64
Windows v.win11_dt
CPU: sse42 avx avx2 avx512
Args: "C:\Users\Tommy\.bun\bin\bun.exe" "build" "--minify" "--target=bun" "--outdir=out/cli" "src/cli/build.ts" "src/cli/build-standalone/index.ts"
Features: Bun.stderr(5) Bun.stdin(4) Bun.stdout(4) bunfig jsc(3) macros(8) tsconfig(12) tsconfig_paths(6)
Builtins: "node:fs" "node:module" "node:os" "node:path" "node:process" "node:tty" "node:url"
Elapsed: 201ms | User: 78ms | Sys: 140ms
RSS: 0.27GB | Peak: 0.27GB | Commit: 0.40GB | Faults: 68113

panic(thread 20140): attempt to use null value
Crashed while visiting C:\Users\Tommy\Documents\brisa-test\brisa\packages\brisa\src\utils\client-build\process-i18n\index.ts
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.2.9/wb19a329c0MukgwgBsp28I0h/0Is+u0ak3z2Z+1h5X2nonnBwnliW8o10U2y3zUqvsnTA0eNpLLClJzS0oUSjJVygtTlXIK83JUShLzClNBQB82AmI

oh no: multiple threads are crashing
panic(thread 31328): attempt to use null value
Crashed while visiting C:\Users\Tommy\Documents\brisa-test\brisa\packages\brisa\src\utils\client-build\pre-entrypoint-analysis\index.ts
 https://bun.report/1.2.9/wb19a329c0MukgwgBsp28I0h/0Is+u0ak3z2Z+1h5X2nonnBwnliW8o10UqvsnT69m1RA0eNpLLClJzS0oUSjJVygtTlXIK83JUShLzClNBQB82AmI

Error importing macro
error: Cannot find package 'astring' from 'C:\Users\Tommy\Documents\brisa-test\brisa\packages\brisa\src\utils\ast\index.ts'
Error importing macro
error: script "build:cli-utils" exited with code 134
error: script "build:bin" exited with code 134
error: script "build:core" exited with code 134
error: script "build" exited with code 134
```

**Comment by aralroca** [comment]
@tommy141x please report this issue to Bun directly  https://bun.report/1.2.9/wb19a329c0MukgwgBsp28I0h/0Is+u0ak3z2Z+1h5X2nonnBwnliW8o10U2y3zUqvsnTA0eNpLLClJzS0oUSjJVygtTlXIK83JUShLzClNBQB82AmI these Bun panic issue should be fixed on the Bun core. Thanks

**Comment by icmedev** [comment]
will this ever be fixed? been waiting since last year for this issue to be resolved

**Comment by aralroca** [comment]
@icmedev I’ve reassigned this to myself. It’s not resolved yet—apologies for the inconvenience. I’ll prioritize it. 👌 Windows is quite important!

Currently, we’re updating the build process in this task: [#628](https://github.com/brisa-build/brisa/issues/628). Ideally, we’ll fix both issues and ensure the new build process works correctly on Windows as well.

**Comment by aralroca** [comment]
@icmedev @LUISMAGAIVER341 @BrainInJar The action fix is working at [0.2.14-canary.2](https://github.com/brisa-build/brisa/releases/tag/0.2.14-canary.2), I still leave open the task to check and fix more Windows stuff.

**Comment by RainyPixel** [comment]
Canary release still have this problem

```bash
$ brisa dev
[ info ]   🚀 Brisa 0.2.14-canary.2: Running on Bun.js 1.2.13
[ wait ]  starting the development server...
[ wait ]  compiling 3 server entrypoints...
[ wait ]  compiling server actions...
[ wait ]  analyzing and preparing client build...
[ wait ]  compiling 1 client entrypoints...
[ error ]   Ops! Error:
[ error ]   --------------------------
[ error ]   Failed to build
[ error ]   ENOENT: no such file or directory, open 'F:\Projects\rainypixel\decomposer\build\pages-client\_rpc.txt'
[ error ]   --------------------------
[ error ]   Error: ENOENT: no such file or directory, open 'F:\Projects\rainypixel\decomposer\build\pages-client\_rpc.txt'
    at readFileSync (unknown)
    at Ts (F:\Projects\rainypixel\decomposer\node_modules\brisa\out\cli\build.js:503:3492)
    at Dp (F:\Projects\rainypixel\decomposer\node_modules\brisa\out\cli\build.js:503:2526)
    at processTicksAndRejections (native:7:39)
[ info ]   hot reloading enabled
[ info ]   listening on http://localhost:3000
```

**Comment by aralroca** [comment]
Thanks for the feedback @SpeedySH, I fixed an async race condition in [0.2.14-canary.4](https://github.com/brisa-build/brisa/releases/tag/0.2.14-canary.4) pre-release, which is probably the root of this problem. I will check on Windows later, since I now have a Mac. But I will be able to check it out this afternoon. Let's see if we can release it soon, because now, between my vacations and travels, it's been a while since I've released a new release 😊 It would be great if the next release had all the Windows stuff correctly.

**Comment by LUISMAGAIVER341** [comment]
Just to try understand.
Does brisa works on top of Vite?
If yes, this glitch could be happening because Vite does not handle path very well. Not only in windows.
If possible, I recommend migrating from vite to webpack + babel.js
Just in case it's Vite based LoL

**Comment by aralroca** [comment]
It's on top of Bun builder right now @LUISMAGAIVER341  https://bun.com/docs/bundler

**Comment by Atharva1723** [comment]
There are still some of issues while running the build , It appends the temp path in front of the build folder : 

<img width="1590" height="397" alt="Image" src="https://github.com/user-attachments/assets/04e68812-87ce-43fc-a6e8-c835039ea229" />

**Comment by aralroca** [comment]
yes, we know @Atharva1723 , thanks to report it. PR are very welcome to fix these window errors
